package com.mrlii.ems.domain.entity.employee;

import com.mrlii.ems.domain.entity.base.SoftDeletableEntity;
import com.mrlii.ems.domain.entity.checklist.EmployeeChecklist;
import com.mrlii.ems.domain.entity.document.EmployeeDocument;
import com.mrlii.ems.domain.entity.organization.Department;
import com.mrlii.ems.domain.entity.organization.EmploymentType;
import com.mrlii.ems.domain.entity.organization.JobRole;
import com.mrlii.ems.domain.enums.EmployeeStatus;
import com.mrlii.ems.domain.enums.Gender;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Past;
import jakarta.validation.constraints.Size;
import lombok.AccessLevel;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "employees")
@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
public class Employee extends SoftDeletableEntity {

    // Immutable after creation — generated by the system, never changed
    @Setter(AccessLevel.NONE)
    @Column(name = "employee_number", nullable = false, unique = true, length = 20, updatable = false)
    private String employeeNumber;

    @NotBlank
    @Size(max = 100)
    @Column(name = "first_name", nullable = false, length = 100)
    private String firstName;

    @NotBlank
    @Size(max = 100)
    @Column(name = "last_name", nullable = false, length = 100)
    private String lastName;

    @NotBlank
    @Email
    @Size(max = 255)
    @Column(name = "email", nullable = false, unique = true, length = 255)
    private String email;

    @Size(max = 20)
    @Column(name = "phone", length = 20)
    private String phone;

    @Past
    @Column(name = "date_of_birth")
    private LocalDate dateOfBirth;

    @Enumerated(EnumType.STRING)
    @Column(name = "gender", length = 20)
    private Gender gender;

    @Size(max = 255)
    @Column(name = "address_line1", length = 255)
    private String addressLine1;

    @Size(max = 255)
    @Column(name = "address_line2", length = 255)
    private String addressLine2;

    @Size(max = 100)
    @Column(name = "city", length = 100)
    private String city;

    @Size(max = 100)
    @Column(name = "state", length = 100)
    private String state;

    @Size(max = 20)
    @Column(name = "postal_code", length = 20)
    private String postalCode;

    @Size(max = 100)
    @Column(name = "country", length = 100)
    private String country;

    @Size(max = 50)
    @Column(name = "national_id", unique = true, length = 50)
    private String nationalId;

    @Column(name = "profile_photo_url", length = 500)
    private String profilePhotoUrl;

    @Column(name = "hire_date")
    private LocalDate hireDate;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "employment_type_id")
    private EmploymentType employmentType;

    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private EmployeeStatus status = EmployeeStatus.PENDING;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "department_id")
    private Department department;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "job_role_id")
    private JobRole jobRole;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "line_manager_id")
    private Employee lineManager;

    @Size(max = 100)
    @Column(name = "emergency_contact_name", length = 100)
    private String emergencyContactName;

    @Size(max = 20)
    @Column(name = "emergency_contact_phone", length = 20)
    private String emergencyContactPhone;

    @Size(max = 50)
    @Column(name = "emergency_contact_relationship", length = 50)
    private String emergencyContactRelationship;

    @OneToMany(mappedBy = "lineManager", fetch = FetchType.LAZY)
    private List<Employee> directReports = new ArrayList<>();

    @OneToMany(mappedBy = "employee", fetch = FetchType.LAZY)
    private List<EmploymentHistory> employmentHistory = new ArrayList<>();

    @OneToMany(mappedBy = "employee", fetch = FetchType.LAZY)
    private List<EmployeeDocument> documents = new ArrayList<>();

    @OneToMany(mappedBy = "employee", fetch = FetchType.LAZY)
    private List<EmployeeChecklist> checklists = new ArrayList<>();

    @OneToMany(mappedBy = "employee", fetch = FetchType.LAZY)
    private List<ProfileUpdateRequest> profileUpdateRequests = new ArrayList<>();

    // ──────────────────────────────────────────────────────────
    // Bidirectional helper methods
    // ──────────────────────────────────────────────────────────

    public void addDirectReport(Employee report) {
        directReports.add(report);
        report.lineManager = this;
    }

    public void removeDirectReport(Employee report) {
        directReports.remove(report);
        report.lineManager = null;
    }

    public void addEmploymentHistory(EmploymentHistory history) {
        employmentHistory.add(history);
        history.setEmployee(this);
    }

    public void addDocument(EmployeeDocument document) {
        documents.add(document);
        document.setEmployee(this);
    }

    public void removeDocument(EmployeeDocument document) {
        documents.remove(document);
        document.setEmployee(null);
    }

    public void addChecklist(EmployeeChecklist checklist) {
        checklists.add(checklist);
        checklist.setEmployee(this);
    }

    public void addProfileUpdateRequest(ProfileUpdateRequest request) {
        profileUpdateRequests.add(request);
        request.setEmployee(this);
    }

    // ──────────────────────────────────────────────────────────
    // Builder
    // ──────────────────────────────────────────────────────────

    @Builder
    public Employee(String employeeNumber, String firstName, String lastName, String email,
                    String phone, LocalDate dateOfBirth, Gender gender, String addressLine1,
                    String addressLine2, String city, String state, String postalCode,
                    String country, String nationalId, String profilePhotoUrl,
                    LocalDate hireDate, EmploymentType employmentType, EmployeeStatus status,
                    Department department, JobRole jobRole, Employee lineManager,
                    String emergencyContactName, String emergencyContactPhone,
                    String emergencyContactRelationship) {
        this.employeeNumber = employeeNumber;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.phone = phone;
        this.dateOfBirth = dateOfBirth;
        this.gender = gender;
        this.addressLine1 = addressLine1;
        this.addressLine2 = addressLine2;
        this.city = city;
        this.state = state;
        this.postalCode = postalCode;
        this.country = country;
        this.nationalId = nationalId;
        this.profilePhotoUrl = profilePhotoUrl;
        this.hireDate = hireDate;
        this.employmentType = employmentType;
        this.status = status != null ? status : EmployeeStatus.PENDING;
        this.department = department;
        this.jobRole = jobRole;
        this.lineManager = lineManager;
        this.emergencyContactName = emergencyContactName;
        this.emergencyContactPhone = emergencyContactPhone;
        this.emergencyContactRelationship = emergencyContactRelationship;
    }
}
