spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ems}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:none}

  graphql:
    graphiql:
      enabled: true

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.security: DEBUG
    org.springframework.graphql: DEBUG
    org.amalitech.armsloanservicepro: DEBUG
    org.apache.kafka: INFO
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

allowed:
  cors:
    url: ${ALLOWED_CORS_URL}

jwt:
  publicKey: ${JWT_PUBLIC_KEY}
  privateKey: ${JWT_PRIVATE_KEY}
  expirationMs: ${JWT_EXPIRATION_MS:28800000}
  refreshExpirationMs: ${JWT_REFRESH_EXPIRATION_MS:604800000}
  cookieSecure: ${JWT_COOKIE_SECURE:false}

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}