package com.mrlii.ems.common.exception.graphql;


public enum GraphQLErrorCode {
	INPUT_VALIDATION_ERROR,
	VALIDATION_ERROR,
	NOT_FOUND,
	BUSINESS_RULE_VIOLATION,
	FORBIDDEN,
	UNAUTHENTICATED,
	INVALID_DATE_FORMAT,
	INVALID_DATE_VALUE,
	DUPLICATE_RECORD,
	DATA_INTEGRITY_VIOLATION,
	DATABASE_ERROR,
	INVALID_PROPERTY_REFERENCE,
	INTERNAL_ERROR
}