type EmployeeDetailResult {
    id: ID!
    firstName: String!
    lastName: String!
    workEmail: String!
    status: CommonStatus!
    position: PositionListItemResult
    department: DepartmentDetailResult
    accessLevel: AccessLevelListItemResult
    bio: EmployeeBioResult
    contact: EmployeeContactResult
    addresses: [EmployeeAddressResult!]!
    identifications: [EmployeeIdentificationResult!]!
    createdDate: DateTime!
    lastModifiedDate: DateTime
}

type EmployeeListItemResult {
    id: ID!
    firstName: String!
    lastName: String!
    email: String!
    jobTitle: String
    department: String
    status: CommonStatus
}

type EmployeePageResult {
    data: [EmployeeListItemResult!]!
    currentPage: Int!
    totalPages: Int!
    totalElements: Int!
    pageSize: Int!
    hasNext: Boolean!
    hasPrevious: Boolean!
}

type EmployeeBioResult {
    fullName: String
    otherName: String
    gender: String
    nationality: String
    maritalStatus: String
    dateOfBirth: String
    placeOfBirth: String
    profilePicture: String
    dateHired: String
    isExpert: String
}

type EmployeeContactResult {
    phoneNumbers: [String!]
    personalEmails: [String!]
}

type EmployeeAddressResult {
    id: ID!
    street: String
    city: String
    state: String
    zipCode: String
    country: String
    digitalAddress: String
    isCurrentAddress: Boolean
}

type EmployeeIdentificationResult {
    id: ID!
    identificationNumber: String!
    identificationType: IdentificationType!
}
